kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: hugging-face-accelerate # hugging-face-accelerate folder
  dockerfile: ./Dockerfile

spec:
  operator: pytorch
  image: image
  command: "env NCCL_P2P_DISABLE=\"1\" NCCL_IB_DISABLE=\"1\" torchrun --nproc_per_node 1 main.py --mixed_precision fp16 --model openai-community/gpt2" # --nproc_per_node=={Number of GPUs}

  tensorboard:
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 4
        ramRatio: 16 # 32GB
        accelerators: # optional
          gpu:
            count: 1
            type: gpu
            product: a10g
